'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Suggestion

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''FirstGreyBar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FirstGreyBar As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''BackButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BackButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''suggestionPageErrorLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents suggestionPageErrorLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''suggestionPageErrorLabel0 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents suggestionPageErrorLabel0 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mainRadioButtonList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mainRadioButtonList As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''general control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents general As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''suggestionPageGeneralLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents suggestionPageGeneralLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''suggestionPageGeneralTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents suggestionPageGeneralTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''GeneralSubmitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GeneralSubmitButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''kopitiam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents kopitiam As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''suggestionPageKopitiamLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents suggestionPageKopitiamLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''suggestionPageKopitiamStateDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents suggestionPageKopitiamStateDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlDataSource1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource1 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''suggestionPageKopitiamNameTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents suggestionPageKopitiamNameTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''suggestionPageKopitiamStartHoursDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents suggestionPageKopitiamStartHoursDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''suggestionPageKopitiamStartMinutesDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents suggestionPageKopitiamStartMinutesDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''suggestionPageKopitiamEndHoursDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents suggestionPageKopitiamEndHoursDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''suggestionPageKopitiamEndMinutesDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents suggestionPageKopitiamEndMinutesDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''suggestionPageKopitiamDaysCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents suggestionPageKopitiamDaysCheckBox As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''suggestionPageKopitiamAddressTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents suggestionPageKopitiamAddressTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''suggestionPageKopitiamHalalRadioButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents suggestionPageKopitiamHalalRadioButton As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''KopitiamSubmitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents KopitiamSubmitButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''stall control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents stall As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''suggestionPageStallLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents suggestionPageStallLabel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ListKopitiamDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListKopitiamDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''MoreFilterCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MoreFilterCheckBox As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''MoreFilterPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MoreFilterPanel As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''KopitiamNameTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents KopitiamNameTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''KopitiamAddressTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents KopitiamAddressTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''KopitiamStateDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents KopitiamStateDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SearchButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''suggestionPageStallFoodDropDown control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents suggestionPageStallFoodDropDown As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SqlDataSource2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDataSource2 As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''suggestionPageStallNameTextBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents suggestionPageStallNameTextBox As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''suggestionPageStallStartHoursDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents suggestionPageStallStartHoursDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''suggestionPageStallStartMinutesDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents suggestionPageStallStartMinutesDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''suggestionPageStallEndHoursDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents suggestionPageStallEndHoursDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''suggestionPageStallEndMinutesDropDownList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents suggestionPageStallEndMinutesDropDownList As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''suggestionPageStallDaysCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents suggestionPageStallDaysCheckBox As Global.System.Web.UI.WebControls.CheckBoxList

    '''<summary>
    '''suggestionPageStallHalalRadioButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents suggestionPageStallHalalRadioButton As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''StallSubmitButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StallSubmitButton As Global.System.Web.UI.WebControls.Button
End Class
